### ISSUE TITLE
Any command from soft to LDG AT-1000PROII not working...

### ISSUE THREAD

**Issue by Eugen68** [Efpophis/LDGControl#6]
The software is connecting to ATU at 38400bps and reading the state of ATU. When I transmit, Meter and Band are indicating correct the parameters.
But others buttons - Bypass, Antenna 1, Full Tune, Memory Tune - not working at all.
With other software this commands sendded to the ATU its working.

**Comment by Efpophis** [comment]
Hi @Eugen68 - 

I am trying to debug this, which is difficult since it works perfectly on my computer with my tuner.

With that in mind, I have added a bunch of debug code to get some output that might tell me what's going on.

If you can, please install and run the attached version, connect to your tuner, and do a MEMORY tune -that is the button I've instrumented.  Please run the program from the command line, capture any output you see (there should be a lot), and post it here.
[Installer_debug_only.zip](https://github.com/user-attachments/files/18152404/Installer_debug_only.zip)

**Comment by dtrewren** [comment]
Sure I will run the debug software.
I attached my oscilloscope to the TX line of the USB adapter to monitor data to the tuner.  I notice that non-working versions 1.6.0.2 and later send a different init data sequence to the tuner compared to the working 1.5.0.13 and earlier versions.

I am an electronics engineer (chip designer) so have built a lot of control systems using both USB and serial comms so I am sure we can debug this.

**Comment by dtrewren** [comment]
I tried to unpack the ZIP file but my machine says there is a virus (trojan) embedded.  I get the same issue with a number of the later versions of the application but not ealier versions.

**Comment by Efpophis** [comment]
That's gotta be a false positive - there's nothing in there but the exe from the code I wrote. And all I did was add some debug output.

Your observation with the scope gave me an idea, tho - I did shorten the "wake up" command between those versions. That explains the different output you're seeing, and I wonder if it might explain the behavior - maybe I'm not waiting long enough for the tuner to wake up before sending the command.

Is there any way you can monitor both the tx and rx lines and see if you get a response at all?  If the tuner isn't answering at all, then that's probably what's going on.  Meanwhile, I'm going to build and publish an update soon (after I test it on mine) that restores the longer "wake up" command and gives it a little more time to do its thing. Maybe that will solve it ...

Anyway, I just scanned the ZIP myself with my brand new Win 11 laptop and the latest defender stuff - it didn't find any threats. My guess is that it's just because Defender is not familiar with this executable (since it's brand new today). FYI, I have my computer configured in "developer mode" so it won't bother me about that stuff. :)

**Comment by Efpophis** [comment]
Please try [Version 1.8.0.1](https://github.com/Efpophis/LDGControl/releases/tag/LDGControl_v1.8.0.1) - I believe I have fixed this issue. At the very least, it works again on my machine with a local serial port connection.

If it works for you, please close the issue.

73,

Bill WK2X

**Comment by Eugen68** [comment]
Hello again,
Thanks for the new version, now seems to work OK...

73
Eugen YO9VA

**Comment by Efpophis** [comment]
Awesome! I'm going to go ahead and close this issue, then. 

Thanks for letting me know.
